FROM php:8.1-apache

RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    && docker-php-ext-install zip

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory
WORKDIR /var/www/html

# Use the default entrypoint of the image
# ENTRYPOINT ["/usr/local/bin/docker-php-entrypoint"]

# Set the command to our custom script
# CMD ["/var/www/html/docker-entrypoint.sh"]

# Copy composer.json and composer.lock
# COPY www/composer.json www/composer.lock* ./

# Install dependencies
# RUN composer install --no-scripts --no-autoloader

# Copy the rest of the application
# COPY www .

# Generate autoloader
# RUN composer dump-autoload --optimize

# CMD apache2-foreground
